### ISSUE TITLE
Improved formatting and display of citations and publication details

### ISSUE THREAD

**Issue by spl** [dragonfly-science/website#10]
This issue is based on a conversation with @finlay. It is an attempt to clarify the goals of presenting the publications. A related issue is #9.

These are the primary goals of publication presentation (the *emphasized part* is for reference):

1. *Format-Citations* – support custom styling/formatting of citations (as found on the old website)
2. *Display-All-Citations* – display all citations, sorted by date, grouped by year
3. *Display-Selected-Citations* – display referenced citations
4. *Display-Details* – display one page per publication with detailed information (e.g. abstract and links) and link the summary from the citation above

These are secondary (but nice to have) goals:

1. *Format-Summaries* – support custom styling/formatting of per-publication detail pages
2. *Display-Author-Citations* – display citations by author, sorted
3. *Display-Tag-Citations* – display citations by tag, sorted
4. *Single-Source* – use a single BibTeX (or other) file as the source for both the website (to generate citations and details) and other publications (to generate a reference section)

**Comment by spl** [comment]
Consider the above a living spec. Please comment on what you think of the goals, the description and ranking, etc. We can change and expand it as necessary.

If I understand it, the current implementation handles *Format-Citations* and *Display-Selected-Citations*, though I believe @finlay said the formatting in the former needs to be better.

**Comment by spl** [comment]
While considering *Format-Summaries*, I think it would be nice to use Markdown for the abstracts: it's consistent with the text of the rest of the website, and it allows more formatting (for the web) than the BibTeX abstract gives you now. If you think that's a good idea, then what about turning each citation into a Markdown document with the citation information in the metadata and the abstract in the text? The downside is that you don't get *Single-Source*, but that may not be so bad. I'm not convinced it's useful to try to keep a document with LaTeX formatting as the source for HTML: there are always issues I've run into when trying to support multiple targets.

**Comment by finlay** [comment]
Hi @spl 

Really nice to talk yesterday. We are happy to proceed with this work. I will set up an account for you on our timesheet system, etc. see email.

Thanks for summarising so well my rambling discussion! I propose to split the work into a few separate enhancements, as follows:

_Single-Source_: 
We want to maintain the .bib file as our main source for citations. However we need store additional information about some of the citations, and this would be in the form of extra markdown files. See #11. Essentially this would allow use to use the single source for base information, with additional files for website specific stuff.

_Format-Citations_ : 
  The main difference is to have links associated, and to have links to the summary page for selected items. Also more control over the HTML. Guess is that this can be done with a custom CSL format, combined with some understanding of what pandoc does. #12

_Display-Details_ and _Format-Summaries_:
  A details page for the selected citations. This is supported by the work in #11.  See #13.

_Display-All-Citations_,  _Display-Selected-Citations_, _Display-Author-Citations_, and _Display-Tag-Citations_:  
  These cases are essentially the same. At a first step we can simply create lists of references by listing reference tags. However, we would like to provide a mechanism for generating lists of reference keys according to query criteria, such as publication date, tags, author, or other criteria. This is certainly the lowest on the list of requirements at the moment.  It would be good to check with how this dovetails with other work going on in the scholarly markdown space. See #14

Over all, work down should be contributed back to the pandoc and pandoc-citeproc projects where appropriate. We are happy to support the effort to do that.
