### ISSUE TITLE
Additional citation information

### ISSUE THREAD

**Issue by finlay** [dragonfly-science/website#11]
We need to add custom information to the citations. There are a few parts to this:
  * the summary / abstract, which ideally should be general markdown, processed in the usual pandoc way. This content is currently in the dragonfly.bib file, but it shouldn't be.
  * links to external publishers, such as journals or government publications series.
  * links to PDF files on our own site
  * other things we haven't thought of yet. Perhaps license information, or free access status.

The extra information is used to augment the _Format-Citation_ in listings, and to provide a _Display-Details_ page.

We propose to add a `publications` folder,  with files named after the .bib cite key: 
```
   publications/<cite_key>.md 
```
These files would contain additional information in the yaml header, for example links to external publishers (MPI, journals etc). The body of the yaml would be used to provide the summary body. 

See discussion in #9 and #10.

**Comment by spl** [comment]
The Markdown file support is mostly done in #17, barring some missing context fields that could be added as needed.

**Comment by edwardabraham** [comment]
RIght, now it is working. Tell me how to put this to use. In particular, I need to modify the template so that I can get the following for a citation:
* a link to the the summary page 
* links to PDF files (with a url, and text to be displayed in the link)

With this in place, I will be able to modify the template for the publications list to get something like what we already have:
https://www.dragonfly.co.nz/publications.html

**Comment by spl** [comment]
Here's what I would do:

1. Modify `content/template/citation-entry.html` to add: `$summaryLink$`, `$pdfLink$`, and `$pdfText$` in the desired style. You will probably want `$if(..)$` around at least the PDF fields.
2. Modify `haskell/WebSite/Context.hs` to change `refContext` to include the `summaryLink` field in the context and fill it in with the appropriate link.
3. Add `pdfLink` and `pdfText` fields to the YAML metadata of your choice of `publications/*.md` files.

I'm currently working on #12, but if I get something working before the end of the day, I'll do the above.

**Comment by edwardabraham** [comment]
Ok, I wasn't quite sure how to add the `summaryLink`, so I added in the `id` to `refContext` and am using that to construct the links in the template. Not exactly ideal, but it works. I am now in a position to fiddle with the layout of the summary pages, and with the citation entries, so I will close this issue.

The commit reduces the references to Katrin's citations. I will gradually build up the publiction mrkdown files (Katrin had been working on dragonfly.bib, so I will take them from there. Unfortunately, they will need to be turned from bibtex latex into markdown/unicode).
67dd4b940e23fc2af64f2afa31643de132a0a052

**Comment by edwardabraham** [comment]
Have a look at `/publications/berkenbusch_distribution_2015.html` to see it in action
