### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by edwardabraham** [dragonfly-science/website#24]
Implement tagging

**Comment by edwardabraham** [comment]
Tagging is now in place for publications. Tags may be specified by putting them in as query parameters into the URL. For example to get all publications by Katrin on marine biology, go to the page `/publications/?tag=katrin,marine-biology`

In order to edit the tags in a bulk way:
1. Change to the `content/publications` directory
2. Use grep to update `tags.csv`, e.g., `grep tags: *.md > tags.csv`
3. Edit the file accordingly
4. Run `./tags_update.py` to copy the new tags into the `md` files

**Comment by katrin-berkenbusch** [comment]
Primary literature including book chapters will be tagged with "article"

**Comment by katrin-berkenbusch** [comment]
We will need a tag for the acoustics work, kiwi calls and maori language recognition

**Comment by katrin-berkenbusch** [comment]
"acoustic"?

**Comment by edwardabraham** [comment]
Sounds good (there aren't many in this category, but they are worth highlighting ...)

**Comment by katrin-berkenbusch** [comment]
I am tagging theses as "report" unless we want to have another tag
