### ISSUE TITLE
Old damselfly for the web page icon?

### ISSUE THREAD

**Issue by yvanrichard** [dragonfly-science/website#29]
Shouldn't the damselfly be replaced by the new logo?

**Comment by edwardabraham** [comment]
Yep. Indeed.

On 3 August 2015 at 13:10, Yvan Richard <notifications@github.com> wrote:

> Shouldn't the damselfly be replaced by the new logo?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dragonfly-science/website/issues/29>.
>



-- 

Edward Abraham
www.dragonfly.co.nz
Dragonfly Science, PO Box 27535, Wellington 6141, New Zealand
Level 5, 158 Victoria Street, Te Aro, Wellington
M: +64 21 989 454
T: +64 4 385 9285

**Comment by katrin-berkenbusch** [comment]
Hi Yvan,

I am just checking this reference, do you have a PDF file?

@InProceedings{	  boulinier_habitat_2000,
  title		= "Habitat selection based on conspecifics: local
		  reproductive success affects attendance and prospecting of
		  future potential breeders",
  author	= "Thierry Boulinier and K. D. {McCoy} and Yvan Richard and T
		  Tveraa",
  year		= "2000",
  address	= "7th Seabird Group Conference, 17--19 March 2000, Wilhelmshaven, Germany”
}

Cheers,
Katrin

**Comment by mermop** [comment]
This is fixed by 405df06fc0194b12b0934a782ee6fcf0b81cd45d
