### ISSUE TITLE
omission of publication

### ISSUE THREAD

**Issue by katrin-berkenbusch** [dragonfly-science/website#58]
My latest publication got taken off...?

**Comment by edwardabraham** [comment]
Yeah. You need to put a record in the bibliography file. I just put a
squiggle at the end of the filename, as it was stopping the website going
live!

**Comment by katrin-berkenbusch** [comment]
ooopsss, I knew I had forgotten something. I’ll do it on Monday.

**Comment by katrin-berkenbusch** [comment]
D'oh! Now I remember, I did add it to the bib.file, but I forgot to sync.
