### ISSUE TITLE
Publications

### ISSUE THREAD

**Issue by edwardabraham** [dragonfly-science/website#9]
We are using bibtex to store publication data. I need to be able to customize the output beyond just the reference. 

*Ideally* we have it so that each reference can have its own page, which includes the abstract (stored in the bibtex), but also links to the pdf and possible other resources. This would work if we were able to use information from the reference in a context that is available to a template. Maybe something like: $title$, $year$, $citation$, $abstract$, $pdf$, $tags$, $people$. The bibtex key could be used to map urls to references. We would also need a way to format lists of references, and a way to generate those lists so they can be used in the templates.

One approach is to define a single YAML file that adds additional information to all the references, something like

abraham_seabirds_2013:
     pdf: seabird-bycatch-in-new-zealand-fisheries.pdf
     people: abraham-edward
     tags: dragonfly, bycatch

The tags and people information can then be used to make lists of references, and can be used for linking to authors (so that we can get a list of all publications by abraham-edward, for example).

This may take a few iterations to get right.

**Comment by finlay** [comment]
This issue has been replaced by #11, #12, #13.
